import { Inter, Roboto } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { NextAuthProvider } from "./Providers";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={'${inter.className} ${roboto.className}'}>
      <NextAuthProvider>
        <body>
          <Head>
            <link rel="icon" href="/favicon.ico" />
            <title>{metadata.title}</title>
          </Head>
          <Navbar />
          {children}
          <Footer />
        </body>
      </NextAuthProvider>
    </html>
  );
}
