import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import { NextAuthProvider } from './Providers'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <Head>
            <link rel="icon" href="/favicon.ico" />
            <title>{metadata.title}</title>
            {/* Add other common meta tags here */}
          </Head>
          <Navbar />
          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  )
}
